language: go
sudo: false
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

cache:
  directories:
    - vendor

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
